//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BidMyCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarDetail
    {
        public int CarID { get; set; }
        public int YOM { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string BodyType { get; set; }
        public string Condition { get; set; }
        public string Category { get; set; }
        public string Features { get; set; }
        public string CarDescription { get; set; }
        public string CarLocation { get; set; }
        public System.DateTime UploadDate { get; set; }
        public int Price { get; set; }
        public int UserID { get; set; }
        public string Color { get; set; }
        public int Miles { get; set; }
        public string Transmission { get; set; }
        public string EngineSize { get; set; }
        public string PowerOutput { get; set; }
        public List<string> VehicleImages { get; set; }
        public string Status { get; set; }
        public string Rating { get; set; }

        public string Currency { get; set; }


    }
}
