//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BidMyCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleImage
    {
        public int ImageID { get; set; }
        public int CarID { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public string Image4 { get; set; }
        public string Image5 { get; set; }
        public string Iframe { get; set; }
        public string Youtube { get; set; }
        public string Vimeo { get; set; }
    }
}
